/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatternIdRouteImport } from './routes/pattern.$id'

const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternIdRoute = PatternIdRouteImport.update({
  id: '/pattern/$id',
  path: '/pattern/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/patterns': typeof PatternsRoute
  '/pattern/$id': typeof PatternIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/patterns': typeof PatternsRoute
  '/pattern/$id': typeof PatternIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/patterns': typeof PatternsRoute
  '/pattern/$id': typeof PatternIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/patterns' | '/pattern/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/patterns' | '/pattern/$id'
  id: '__root__' | '/' | '/about' | '/patterns' | '/pattern/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PatternsRoute: typeof PatternsRoute
  PatternIdRoute: typeof PatternIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern/$id': {
      id: '/pattern/$id'
      path: '/pattern/$id'
      fullPath: '/pattern/$id'
      preLoaderRoute: typeof PatternIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PatternsRoute: PatternsRoute,
  PatternIdRoute: PatternIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
