/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as SparringRouteImport } from './routes/sparring'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SparringIndexRouteImport } from './routes/sparring.index'
import { Route as SparringTypeRouteImport } from './routes/sparring.$type'
import { Route as PatternIdRouteImport } from './routes/pattern.$id'
import { Route as SparringTypeNumberRouteImport } from './routes/sparring.$type.$number'

const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const SparringRoute = SparringRouteImport.update({
  id: '/sparring',
  path: '/sparring',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SparringIndexRoute = SparringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SparringRoute,
} as any)
const SparringTypeRoute = SparringTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => SparringRoute,
} as any)
const PatternIdRoute = PatternIdRouteImport.update({
  id: '/pattern/$id',
  path: '/pattern/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SparringTypeNumberRoute = SparringTypeNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => SparringTypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/sparring': typeof SparringRouteWithChildren
  '/theory': typeof TheoryRoute
  '/pattern/$id': typeof PatternIdRoute
  '/sparring/$type': typeof SparringTypeRouteWithChildren
  '/sparring/': typeof SparringIndexRoute
  '/sparring/$type/$number': typeof SparringTypeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/theory': typeof TheoryRoute
  '/pattern/$id': typeof PatternIdRoute
  '/sparring/$type': typeof SparringTypeRouteWithChildren
  '/sparring': typeof SparringIndexRoute
  '/sparring/$type/$number': typeof SparringTypeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/sparring': typeof SparringRouteWithChildren
  '/theory': typeof TheoryRoute
  '/pattern/$id': typeof PatternIdRoute
  '/sparring/$type': typeof SparringTypeRouteWithChildren
  '/sparring/': typeof SparringIndexRoute
  '/sparring/$type/$number': typeof SparringTypeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patterns'
    | '/sparring'
    | '/theory'
    | '/pattern/$id'
    | '/sparring/$type'
    | '/sparring/'
    | '/sparring/$type/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patterns'
    | '/theory'
    | '/pattern/$id'
    | '/sparring/$type'
    | '/sparring'
    | '/sparring/$type/$number'
  id:
    | '__root__'
    | '/'
    | '/patterns'
    | '/sparring'
    | '/theory'
    | '/pattern/$id'
    | '/sparring/$type'
    | '/sparring/'
    | '/sparring/$type/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatternsRoute: typeof PatternsRoute
  SparringRoute: typeof SparringRouteWithChildren
  TheoryRoute: typeof TheoryRoute
  PatternIdRoute: typeof PatternIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparring': {
      id: '/sparring'
      path: '/sparring'
      fullPath: '/sparring'
      preLoaderRoute: typeof SparringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparring/': {
      id: '/sparring/'
      path: '/'
      fullPath: '/sparring/'
      preLoaderRoute: typeof SparringIndexRouteImport
      parentRoute: typeof SparringRoute
    }
    '/sparring/$type': {
      id: '/sparring/$type'
      path: '/$type'
      fullPath: '/sparring/$type'
      preLoaderRoute: typeof SparringTypeRouteImport
      parentRoute: typeof SparringRoute
    }
    '/pattern/$id': {
      id: '/pattern/$id'
      path: '/pattern/$id'
      fullPath: '/pattern/$id'
      preLoaderRoute: typeof PatternIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparring/$type/$number': {
      id: '/sparring/$type/$number'
      path: '/$number'
      fullPath: '/sparring/$type/$number'
      preLoaderRoute: typeof SparringTypeNumberRouteImport
      parentRoute: typeof SparringTypeRoute
    }
  }
}

interface SparringTypeRouteChildren {
  SparringTypeNumberRoute: typeof SparringTypeNumberRoute
}

const SparringTypeRouteChildren: SparringTypeRouteChildren = {
  SparringTypeNumberRoute: SparringTypeNumberRoute,
}

const SparringTypeRouteWithChildren = SparringTypeRoute._addFileChildren(
  SparringTypeRouteChildren,
)

interface SparringRouteChildren {
  SparringTypeRoute: typeof SparringTypeRouteWithChildren
  SparringIndexRoute: typeof SparringIndexRoute
}

const SparringRouteChildren: SparringRouteChildren = {
  SparringTypeRoute: SparringTypeRouteWithChildren,
  SparringIndexRoute: SparringIndexRoute,
}

const SparringRouteWithChildren = SparringRoute._addFileChildren(
  SparringRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatternsRoute: PatternsRoute,
  SparringRoute: SparringRouteWithChildren,
  TheoryRoute: TheoryRoute,
  PatternIdRoute: PatternIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
